### ISSUE TITLE
Commit Message Capitalisation

### ISSUE THREAD

**Issue by mikejwhat** [compilerla/conventional-pre-commit#108]
My colleagues and I are finding it slightly frustrating that commit messages generated by GitHub Copilot are not accepted by this hook.

For example, I will be pulled up on the auto-generated commit message below due to the capital 'A' after the colon.

![image](https://github.com/user-attachments/assets/a9803251-2e72-4169-8b73-9410a17284ac)

This seems to be at odds with the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/#specification):

**_15. The units of information that make up Conventional Commits MUST NOT be treated as case sensitive by implementors, with the exception of BREAKING CHANGE which MUST be uppercase._**

Can we change this or at least have the ability to opt out of case checking?

**Comment by thekaveman** [comment]
Thanks @mikejwhat

Just looking quickly at the regex for [that section of the commit message](https://github.com/compilerla/conventional-pre-commit/blob/main/conventional_pre_commit/format.py#L57) (called the `subject`):

```python
r" .+$"
```

I'm not seeing anything where a capital letter (or really any character) would be a problem.

Are you sure that is the source of the hook failure?

**Comment by thekaveman** [comment]
Please let us know if you continue to see this issue.
