### ISSUE TITLE
Standard git merge commit messages

### ISSUE THREAD

**Issue by lstanc** [compilerla/conventional-pre-commit#110]
Hi,

Maybe it would be nice to have such functionality that **standard git merge commit messages** are accepted by **conventional-pre-commit** as they are. By that I mean that they don't need to have "feat: " or the other prefixes. I think that would be good to add them as an exception to the validation rule. Below I'm placing example of such kind of message.
Example: commit message "Merge branch 'main' into feature/name-of-a-feature-branch".

**Comment by thekaveman** [comment]
Thank you for the question @lstanc.

This has been discussed at length before, see: #19, #39, #76, #84.

TLDR; we are all about _enforcing Conventional Commits formatting_ here. There are plenty of workarounds / alternate tools if you'd like to avoid this checking in certain scenarios.
