### ISSUE TITLE
Scopes become required in commit messages when using the --scopes flag

### ISSUE THREAD

**Issue by nimaps** [compilerla/conventional-pre-commit#111]
Using v3.4.0

The following commits message, as expected, satisfies the CLI when it is called without arguments:

```
feat: add new feature
```

![image](https://github.com/user-attachments/assets/4a8c8690-3f61-4042-8e8d-8443a7b49316)

However, when used like this (commit-message is the name of the file containing the actual message):

```
conventional-pre-commit --scopes chore,feat,fix,custom commit-message
```

The CLI raises an error saying the it is a bad commit message.

![image](https://github.com/user-attachments/assets/80d57701-8b5c-43d0-bccc-3b0b1d0620a1)

I was trying to configure one of my projects to accept a set of **optional**, predefined scopes. But when i configure the `--scopes` argument in the pre-commit config file, scope becomes mandatory. Is this the expected behavior? Or am I doing something wrong here?

P.S. Thank you for your effort for this great CLI tool. I have been using it in many of my projects and will continue to do so.

**Comment by thekaveman** [comment]
Thanks for your question @nimaps! It looks like this is indeed a bug / not what I would have expected either.

The offending line is here: https://github.com/compilerla/conventional-pre-commit/blob/main/conventional_pre_commit/format.py#L40

If custom `scopes` are provided, the `optional` flag is not being respected and the pattern created is requiring one of those custom scopes.

E.g. for your case with `--scopes chore,feat,fix,custom` we get the following regex for the _scope_ section:

```
\(\s*(?:chore|feat|fix|custom)(?:\s*(?::|,|\-|/)\s*(?:chore|feat|fix|custom))*\s*\)
```

Which actually has two problems:

1. One of `chore|feat|fix|custom` is required at least once, regardless of `optional` (this bug report)
2. There is an unescaped forward slash `/` at the end of the group of separators: `(?::|,|\-|/)`

We would be happy to accept a PR to fix this!

**Comment by nimaps** [comment]
Sure @thekaveman, I believe #113 solves the first one but im not sure about the second problem. Do forward slashes need to be escaped?

**Comment by thekaveman** [comment]
@nimaps 

> Do forward slashes need to be escaped?

No, you are absolutely right --  I was getting confused with other regex flavors. I'll take a look at #113, thanks!
