### ISSUE TITLE
Print the available scopes when it's not in the list

### ISSUE THREAD

**Issue by IlyesSemlali** [compilerla/conventional-pre-commit#124]
In output of this pre-commit hook, we only see that the convention is not followed properly:

```
Your commit message does not follow Conventional Commits formatting
https://www.conventionalcommits.org/

Use the --verbose arg for more information
```

It would be even more helpful if we could have a dedicated error in the output when the hook fails du to invalid scope. The output could be:
```
The scope <scope> isn't defined in the supported list of scopes:
<list of supported scopes>
```
Is that feasible ?

**Comment by thekaveman** [comment]
@IlyesSemlali [`v4.0.0`](https://github.com/compilerla/conventional-pre-commit/releases/tag/v4.0.0) has been released with even more verbose output.

Please re-open if you're still not seeing what you need.
