### ISSUE TITLE
Problems with mark signs

### ISSUE THREAD

**Issue by rgnkn** [compilerla/conventional-pre-commit#15]
There seems to be a problem if the commit message contains any mark signs like `"`, `'`, `backtick`, etc. I guess those signs should be allowed.

[EDIT] To offer an solution I think line 27 should be:

```
r_subject=" [[:print:]].+"
```

**Comment by thekaveman** [comment]
Thanks for the report and the PR @rgnkn!

Would you mind sharing:

* The version of `conventional-pre-commit` you're using
* Your OS and terminal
* An example of the commit you're trying to make, and the problem you're seeing as a result?

Here's a quick sample I put together with `conventional-pre-commit v1.2.0` that shows all three of those characters should work in the subject: https://github.com/compilerla/test-commit-marksigns

This was using Git Bash on Windows 10. I've also confirmed on bash in Debian.

**Comment by rgnkn** [comment]
I will try later and inform you. Maybe it's a weired combination with my setup - I'm using lazygit via neovim on zsh.

**Comment by rgnkn** [comment]
Okay, I checked and it seems to be an issue with lazygit. The problem doesn't occure if committed via plain shell commands.

Basically lazygit escapes the marks: so, instead of 

```
fix: `blub`.
```

It sends this:

```
fix: \`blub\`.
```

Therefore, if you think this is a strange setup - which I assume isn't the case - you can forget about my issue. Otherwise you might consider my PR. I didn't realize this behavior of lazygit before as my tools for viewing commit-history (`tig` in the terminal and `GV` in neovim do not show the escaping, same with the commit details on our `gitlab`).

Setup details:
- lazygit: commit=f91adf026bfbddc9505d6d84d3fabc80d49c7ca0, build date=2021-06-05T04:16:14Z, build source=binaryRelease, version=0.28.2, os=linux, arch=amd64
- neovim: nightly
- zsh: 5.8
- bash: 5.1.8
- kitty: 0.24.4
- ubuntu: 21.10 (impish)

**Comment by rgnkn** [comment]
FYI:

- I also tested now with the latest `lazygit`: same result
- Do you want also to here the rationale behind the other issue I opened ([#16](https://github.com/compilerla/conventional-pre-commit/issues/16#issue-1199125220))? If yes, please advise.

**Comment by rgnkn** [comment]
FYI:

I just quickly checked the git sources and the escaping gets filtered with commit messages. Therefore, what `lazygit` does seems valid and other tools might behave the same.

**Comment by thekaveman** [comment]
Merged #17
