### ISSUE TITLE
Typo in repo topic

### ISSUE THREAD

**Issue by stigok** [compilerla/conventional-pre-commit#20]
Hey! Thank you for this hook. I saw that you have a typo in one of your topics: `convetional-commits ` is missing an `n`.

**Comment by thekaveman** [comment]
Doh! @stigok you are totally correct:

![image](https://user-images.githubusercontent.com/1783439/172250990-da4fe28d-0e88-4e53-a33f-635c806b18ea.png)

I have updated that now, thank you for this amazing find! 🙏  

![image](https://user-images.githubusercontent.com/1783439/172251113-5f100aab-8471-4fc6-b32a-1fc016b7c003.png)
