### ISSUE TITLE
Add to https://pre-commit.com/hooks.html

### ISSUE THREAD

**Issue by wholtz** [compilerla/conventional-pre-commit#24]
Thanks for the useful hook!

 You might consider adding it to https://pre-commit.com/hooks.html so that it is easier for others to discover.

**Comment by thekaveman** [comment]
Thanks for the suggestion @wholtz! I submitted a PR over there.

There is perhaps a question of the maintainers adding new `language: script` type hooks (of which this hook is one) to the page, but maybe an exception can be made in this case since our hook/script is so simple!

**Comment by thekaveman** [comment]
@wholtz after much back and forth with the maintainer of https://pre-commit.com, including completely re-writing this hook in Python to avoid `language: script`, they have declined to accept our PR to add this hook to the list.

I recommend opening a new Issue / PR over there if this is something you would still like to pursue. We appreciate the suggestion nonetheless!
