### ISSUE TITLE
Add ":" (colon) to be valid scope sign

### ISSUE THREAD

**Issue by pmoscode** [compilerla/conventional-pre-commit#34]
Hi,
could you add the colon to "r_scope()" method to be a valid sign?

The colon could be used as a separator for a module chain. (Some kind of parent -> child relation)
Ex.: feat(parent:child)

Or even better: Could you make it configurable? (Inside the ".pre-commit-config.yaml" file)

Greetings

**Comment by thekaveman** [comment]
Thanks for your suggestion and work on this @pmoscode!

The feature is live in the [latest release on PyPI: `v2.1.1.`](https://pypi.org/project/conventional-pre-commit/2.1.1/)
