### ISSUE TITLE
Default message from merge commit should be allowed

### ISSUE THREAD

**Issue by fiksn** [compilerla/conventional-pre-commit#39]
Something like `Merge branch .* into .*` should still ok or am I mistaken?

**Comment by angela-tran** [comment]
Hi @fiksn -

Thanks for the question! I believe https://github.com/compilerla/conventional-pre-commit/pull/19#issuecomment-1133434301 has the answer.

If anyone is curious, I found some additional discussion about this topic:
 - https://github.com/conventional-commits/conventionalcommits.org/issues/197
 - https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#discussion

**Comment by thekaveman** [comment]
Thanks for the suggestion @fiksn. 

@angela-tran has it right though, we'd like to keep this focused on conventional commits formatting. Local merge commit messages can be customized, or you can avoid the check entirely with the `--no-verify` flag, e.g.

```bash
git merge branch --no-verify
```
