### ISSUE TITLE
Allow extra parameters

### ISSUE THREAD

**Issue by guilhermeprokisch** [compilerla/conventional-pre-commit#47]
In my CI I need to include cases as `feat!: message, fix!: some messsage` would be possible to add extra types instead of listing all then in the `args` list?

**Comment by thekaveman** [comment]
Hello @guilhermeprokisch - please see prior discussion on this topic on #4 and #39. Thus far we have been focused on a pure conventional commits implementation so have purposely not supported git merge-like commit messages. As noted elsewhere, running this check in CI is also not exactly the intended use-case; by the time the commit has gotten to CI, it is already too late to block it based on the message! This check is really for local developers before commits are pushed up to shared remotes.

But a little more flexibility is obviously something that folks would appreciate, so we'll be looking into how to implement this, taking into account the constraints around `pre-commit` argument passing etc.

@JP-Ellis proposed an idea https://github.com/compilerla/conventional-pre-commit/issues/4#issuecomment-1486432897 that is a possibility but I'm not a huge fan of mixing the `args` list like that.

**Comment by thekaveman** [comment]
Closing this in favor of the latest iteration of the request in #60
