### ISSUE TITLE
bypass conventional commit format when message match a regex defined by command line option

### ISSUE THREAD

**Issue by ledocc** [compilerla/conventional-pre-commit#76]
Hi,
Thanks for this nice piece of code !

I plan to use it in my organization, but we already use git flow to manage our branching model.
And when git flow merge a branch, the message is:
"Merge branch 'feature/xxx' into develop"
I would like to add a command line option to allow user to define one or many regex. 
If the message match one of the regex, it will be accepted, even if it don’t respect conventionnal commit.

Thought ?

**Comment by thekaveman** [comment]
Hi @ledocc, thanks for reaching out, but this suggestion feels outside of the scope of what this hook is trying to do (enforce Conventional Commits format). 

Some options for your use-case:

1. Edit the merge commit message to conform to Conventional Commits: this is relatively straightforward, `git` brings up the commit message editor by default on merge commits, so you have a chance to edit the message, e.g. from

    ```shell
    Merge branch 'feature/xxx' into develop
    # Please enter a commit message to explain why this merge is necessary,
    # especially if it merges an updated upstream into a topic branch.
    #
    # Lines starting with '#' will be ignored, and an empty message aborts
    # the commit.
    ```
    
    To
    ```shell
    feat: merge branch 'feature/xxx' into develop
    ```
2. Do the merge with the `--no-verify` flag, skipping the check altogether:

    ```shell
    git checkout develop
    git merge --no-verify feature/xxx
    ````
    Here the message can be anything you want (including the default) as the Conventional Commit check will not run

3. Finally, you may find that something like [`gitlint`](https://jorisroovers.com/gitlint/latest/) is more appropriate for your use-case.
