### ISSUE TITLE
colours on non-ansi terminals

### ISSUE THREAD

**Issue by wsourdeau** [compilerla/conventional-pre-commit#81]
Hello, I have discovered by reading the code that the colours codes are used unconditionnally. In the case where the output is piped to a process, those colour code might make the output less easy to read.

It would be nice to either provide a command-line argument to disable the colours and/or use a validation method that ensures that stdout is an actual terminal which supports colours codes.

**Comment by thekaveman** [comment]
Hello @wsourdeau -- thank you for the suggestion, I think it's a great idea and would welcome a PR!
