### ISSUE TITLE
Merge commits don't work

### ISSUE THREAD

**Issue by tobias-feil-plana** [compilerla/conventional-pre-commit#84]
Hello, is there a way to enable merge commits? Mine start with "Merge branch 'master'..."

**Comment by thekaveman** [comment]
Hello @tobias-feil-plana -- thank you for the question.

The TLDR; is that support for merge commits is not entirely clear even in the Conventional Commits spec itself, and we try to stay as close to that spec as possible here. Luckily there are a number of workarounds and alternate tools that may fit your use-cases better than this tool. 

Please see prior threads where we have discussed this, e.g. #39, #76.

**Comment by tobias-feil-plana** [comment]
Hello, thanks for the answer and the links! Sounds good, I'll try to do it that way :+1:

**Comment by Viibrant** [comment]
> Hello [@tobias-feil-plana](https://github.com/tobias-feil-plana) -- thank you for the question.
> 
> The TLDR; is that support for merge commits is not entirely clear even in the Conventional Commits spec itself, and we try to stay as close to that spec as possible here. Luckily there are a number of workarounds and alternate tools that may fit your use-cases better than this tool.
> 
> Please see prior threads where we have discussed this, e.g. [#39](https://github.com/compilerla/conventional-pre-commit/issues/39), [#76](https://github.com/compilerla/conventional-pre-commit/issues/76).

Would it be possible to provide a default? Either a new `merge` type or default ot allowing them?

**Comment by thekaveman** [comment]
Hi @Viibrant 

> Would it be possible to provide a default?

The default is already provided by git, e.g. you can invoke the default behavior on a per-commit basis by using the `--no-verify` flag.

As we've discussed in these issues, this tool will remain focused on checking for Conventional Commits formatting, something that git does not do by default.
