### ISSUE TITLE
Support multiple scopes

### ISSUE THREAD

**Issue by martinp7** [compilerla/conventional-pre-commit#85]
Sometimes it is convenient to specify multiple scopes in a commit message e.g. `feat(pkg1,pkg2): add some feature`. 

## Current behaviour with v3.0.0

The following command is raising an error:
```bash
git commit -m "feat(pkg1,pkg2): add new feature"
```

<details>

<summary>Error</summary>

````
[Bad Commit message] >> feat(pkg1,pkg2): add new feature

        Your commit message does not follow Conventional Commits formatting
        https://www.conventionalcommits.org/

        Conventional Commits start with one of the below types, followed by a colon,
        followed by the commit subject and an optional body seperated by a blank line:

            ci build docs feat fix perf refactor style test EXP

        Example commit message adding a feature:

            feat: implement new API

        Example commit message fixing an issue:

            fix: remove infinite loop

        Example commit with scope in parentheses after the type for more context:

            fix(account): remove infinite loop

        Example commit with a body:

            fix: remove infinite loop

            Additional information on the issue caused by the infinite loop
````

</details>

## Expected behaviour

If the scopes are comma separated, the commit message should be considered as valid :white_check_mark: 

---

This is something supported by other tools to validate commit message e.g. https://github.com/conventional-changelog/commitlint/pull/901

**Comment by thekaveman** [comment]
Thank you for the suggestion @martinp7! 

In reading the [Conventional Commits spec around scopes](https://www.conventionalcommits.org/en/v1.0.0/#specification):

> 4. A scope MAY be provided after a type. A scope MUST consist of a noun describing a section of the codebase surrounded by parenthesis, e.g., fix(parser):

I see nothing that explicitly _forbids_ multiple scopes, and we already support scope separators like ` `, `/`, `-`, and `:` -- so I see no reason why we can't also support `,`.

A PR for this change would be most welcome!

**Comment by martinp7** [comment]
Thanks for the answer, I was not aware that other separators were supported, I can implement it :ok_hand:

**Comment by thekaveman** [comment]
Thanks again for your work on this @martinp7. 

`3.1.0` has been released in [GitHub](https://github.com/compilerla/conventional-pre-commit/releases/tag/v3.1.0) and [PyPI](https://pypi.org/project/conventional-pre-commit/3.1.0/) with this change.
