### ISSUE TITLE
Running with `pre-commit run --all-files`

### ISSUE THREAD

**Issue by jakub-borusewicz** [compilerla/conventional-pre-commit#9]
Hi, I wonder how hook should be configured to be run with `pre-commit run --all-files` command, so I could utilize it with CI. Seems that default stage `[commit-msg]` doesn't work in that case, and when I experimented a little with different `stages` configuration, hook started validating commited files body :/. Any ideas how this issue could be solved? Thanks in advance

**Comment by thekaveman** [comment]
Hi @jakub-borusewicz, thanks for the question -- I too have struggled with this issue!

What you have found when trying to change the stage is at the core of the problem. The `commit-msg` stage presents a file containing the commit message to the hook as an argument. You can read more about the available hooks in the Git Book: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

> The `commit-msg` hook takes one parameter ... the path to a temporary file that contains the commit message written by the developer. If this script exits non-zero, Git aborts the commit process, so you can use it to validate your project state or commit message before allowing a commit to go through.

This is known as a "Client-Side Hook" and is not intended to be run by a remote, it's meant for catching things _before_ the commit gets to the remote (really, before the commit is even made locally). By the time a commit has landed in CI, it's already too late to look at the commit message.

Unfortunately this means the hook cannot be used to gate badly formatted commit messages coming in from external parties on GitHub; the biggest risk here is folks not familiar with the project editing files directly on GitHub for a PR.

For anyone cloning the project and going through the proper dev setup, you can guide them towards configuring `pre-commit` as part of the setup to ensure commits are formatted correctly _before_ they get to your CI. Our team has had a lot of success using [Devcontainers](https://code.visualstudio.com/docs/remote/create-dev-container) and configuring `pre-commit` inside the Devcontainer, ensuring the whole team has a consistent environment.

Take a look at our [`intake-html-table`](/compilerla/intake-html-table) repo for an example of a Devcontainer setup with `pre-commit`. Here's the actual script that runs inside the Devcontainer to do the setup: https://github.com/compilerla/intake-html-table/blob/main/.devcontainer/postcreate.sh#L15

**Comment by thekaveman** [comment]
Hi @jakub-borusewicz - thanks again for your question. I'm going to close this issue now, but feel free to re-open if you have more questions, or open a new issue if you'd like to discuss something else.
