### ISSUE TITLE
Option to force no period at the end of description

### ISSUE THREAD

**Issue by echasnovski** [compilerla/conventional-pre-commit#92]
I would like to suggest adding an option for checking if description does not end with a period (full stop, `.`). Although not explicitly stated in spec, `<description>` in all examples has this property and (as far as I can tell) this is a rule followed by many users of conventional commits.

Possible approaches might be `--force-no-period` (more reasonable) or as part of `--strict`.

**Comment by thekaveman** [comment]
Thanks for the suggestion @echasnovski. I can see the argument for wanting to enforce this behavior. But as you note, this is not mentioned anywhere [in the spec](https://www.conventionalcommits.org/en/v1.0.0/#specification).

My concern is this gets us too far away from _checking for conventional commits formatting_ and closer to something like what [`gitlint`](https://jorisroovers.com/gitlint/latest/) is doing. You may find that using both this tool and something like `gitlint` in combination gets you the validation you are after.

Thanks again!

**Comment by echasnovski** [comment]
Sure, I understand. Seeing previous issues, I thought that this will likely be the response. But as there is `--force-scope` (which is not in the spec), I figured it's worth to ask.

**Comment by thekaveman** [comment]
> But as there is `--force-scope` (which is not in the spec), I figured it's worth to ask.

I appreciate your understanding, and definitely welcome questions/suggestions like this! I think the difference in my mind with `--force-scope` is that the scope is something explicitly defined in the spec, and so it felt more natural to have a flag to enforce its inclusion.
